#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
# Local mirror of the CI dco job: a commit must carry a Signed-off-by trailer.
# pre-commit passes the commit-msg file path as $1.
set -eu
msg_file="$1"
# A merge commit's message is generated by git and carries no sign-off. CI
# excludes them with `git rev-list --no-merges`; without the same exclusion the
# local hook rejects a merge that CI would accept.
if [ -e "$(git rev-parse --git-path MERGE_HEAD 2>/dev/null)" ]; then
  exit 0
fi
if ! grep -qE '^Signed-off-by: .+ <.+@.+>' "$msg_file"; then
  echo "Missing Signed-off-by trailer in the commit message." >&2
  echo "Re-run with:  git commit -s   (or  git commit -s --amend)" >&2
  exit 1
fi
